on: push

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7
      
      - name: list files
        run: tree

      - name: compile
        uses: arduino/compile-sketches@v1.1.2
        with:
          fqbn: rp2040:rp2040:rpipico
          platforms: |
            - name: rp2040:rp2040
              source-url: https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json
          sketch-paths: .

